spring:
  application:
    name: ums
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql:3310/user_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql

jwt:
  secret: 2jX8kPqW3zT2rY8mB5nK4jF6hD1cV0aE2bN9mL7xQ==
  expiration: 3600000